# Joint configuration for joint_state_publisher_gui

joint_state_publisher:
  ros__parameters:
    # Joint names and default positions
    zeros:
      LeftAnklePitch: 0.0
      LeftHipPitch: 0.0
      LeftHipRoll: 0.0
      LeftKneePitch: 0.0
      RightAnklePitch: 0.0
      RightHipPitch: 0.0
      RightHipRoll: 0.0
      RightKneePitch: 0.0

    # Joints to publish
    source_list:
      - LeftAnklePitch
      - LeftHipPitch
      - LeftHipRoll
      - LeftKneePitch
      - RightAnklePitch
      - RightHipPitch
      - RightHipRoll
      - RightKneePitch